version: "3.7"
services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pocketbase-apps
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
      - 8090:8090
      - 8091:8091
      - 8092:8092
      - 8093:8093
    volumes:
      - /Users/nils/VolumesDocker/app1:/app1/pb_data
      - /Users/nils/VolumesDocker/app2:/app2/pb_data
      - /Users/nils/VolumesDocker/app3:/app3/pb_data
      - /Users/nils/VolumesDocker/fightnight:/fightnight/pb_data
